[project]
name = "miller"
version = "0.1.0"
dependencies = [
    "matplotlib >= 3.9",
    "scipy >= 1.14",
    "numpy >= 2.1.0",
]
[project.optional-dependencies]
accel = ["scipy", "bottleneck", "numbagg", "numba>=0.54", "flox", "opt_einsum"]
parallel = ["dask[complete]"]
